version: "3"

services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
  web:
    build: ./web
    depends_on:
      - db
    ports:
      - "5000:5000"
