version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "myappdb"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}
    volumes:
      - .:/app
volumes:
  db-data:
